name: Node.js CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.12.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: '22.12.x'
                  cache: 'npm'
            - run: npm ci
            - run: npm run ci:build
            - run: npm run ci:lint
            - run: npm run ci:test
